### ISSUE TITLE
Choosing devices in GUI breaks icicle

### ISSUE THREAD

**Issue by ryansantos1174** [OSU-CMS/Ph2_ACF_GUI#103]
When connecting to a device without using the default icicle settings, the HV attempts to ramp down without the LV on and causes icicle to freak out breaking the GUI. This should all be in the InstrumentCluster branch. We can either fix this issue and keep the combo boxes for the ports and the devices or we can get rid of the combo boxes and have people setup their devices from the settings file.

**Comment by mlj5j** [comment]
Outdated issue.  Updating and reopening.
