### ISSUE TITLE
Check for Wayland Compatibility 

### ISSUE THREAD

**Issue by ryansantos1174** [OSU-CMS/Ph2_ACF_GUI#124]
A few weeks ago I had gotten an issue while attempting to run the GUI. This issue seemed to stem from my use of display server on linux. I was using the new wayland display server instead of X11. This display server might be used by Alma linux and as time passes the likelihood of wayland being used will increase. Therefore, someone should test opening the GUI within the docker using Alma Linux to make sure that everything launches correctly. The error that would pop up is something about a display not being available.

**Comment by mlj5j** [comment]
We have an issue on the Alma Linux machine with lack of HD space.  We're currently sharing this machine, but that should change very soon.  Once we have the machine to ourselves it might be best to fix the partition sizes and then perform this test.

**Comment by ryansantos1174** [comment]
In order to launch the GUI I was required to run "sudo bash run_Docker.sh". I don't believe this is needed on CentOS but after the GUI seems to open fine. This link was used to get Docker installed https://www.liquidweb.com/kb/install-docker-on-linux-almalinux/
