### ISSUE TITLE
Check HV staying on after IVcurve

### ISSUE THREAD

**Issue by mlj5j** [OSU-CMS/Ph2_ACF_GUI#230]
There was a report that the HV stays on after running a standalone IVCurve.  We should verify that this happens and if so, we need to fix it so that the HV ramps down and turns off after the test is complete.  What should happen after the IVCurve is finished, is that the HV should ramp down to zero and then shutdown.  Once the HV is turned off the LV should then turn off.

**Comment by dziabicki** [comment]
Once an IVCurve is finished, the IVCurveFinished function in TestHandler.py is executed. Within that function, there is a condition that if the test is a composite test, then turn the HV on. Standalone IVCurve is considered a composite test in InnerTrackerTests/TestSequences.py, so this condition is true and the HV is turned on. When moving IVCurve from the composite test list to the Test_to_Ph2ACF_Map, this issue disappears (may need to modify TestValidator.py to accommodate).
