### ISSUE TITLE
Incorrect File Permissions When Running GUI 

### ISSUE THREAD

**Issue by ryansantos1174** [OSU-CMS/Ph2_ACF_GUI#93]
When running the GUI both inside and outside of docker, tests will crash. The underlying issue is that the docker image is ran using sudo. Therefore, when it creates a directory it creates a directory that only the privileged user (su) can access. If you run the test outside of docker, you lack permission to write to those directories and everything crashes. 

A good place to start is here https://github.com/OSU-CMS/Ph2_ACF_GUI/blob/main/Gui/python/TestHandler.py

**Comment by mlj5j** [comment]
No longer needed
